Setup simple server on gateway
evan-schott/ww-load-balancer pull request #3
Opened 2023-04-17 21:52 UTC by evan-schott

Simple net/http server

2023-04-17 21:55 UTC, evan-schott commented
@lthibault

2023-04-17 21:55 UTC, lthibault requested changes

2023-04-17 21:55 UTC, lthibault commented on .vscode/launch.json
> +{
You probably don't want to commit anything under `.vscode/*`

2023-04-17 21:55 UTC, lthibault commented on main.go
> +	log2.Println("starting server, listening on port " + getServerPort())
Just use `logger.Info(...)` instead of importing a separate logging library.

2023-04-17 21:55 UTC, lthibault commented on main.go
> +func getServerPort() string {
This is overkill.  I would just pass `":8080"` to `ListenAndServe` directly.

2023-04-17 21:55 UTC, lthibault commented on main.go
> +		counter := 0
What is this for?

2023-04-17 22:55 UTC, lthibault requested changes

2023-04-17 22:55 UTC, lthibault commented on main.go
> +	writer.Header().Set("Access-Control-Allow-Origin", "*")
Setting headers is unnecessary.  I'd remove this from both handlers, just to keep the visual noise down.

2023-04-17 22:56 UTC, lthibault requested changes

2023-04-17 22:56 UTC, lthibault commented on main.go
> +	var payload map[string]interface{}
Recommend defining a struct for this.  Maps are a PITA to use with JSON.

2023-04-18 00:00 UTC, lthibault commented on main.go
> +	log.Info("Slightly echoing back request made to " + request.URL.Path + " to client (" + request.RemoteAddr + ")")
Just FYI:  you can use `logger.Infof("slightly echoing back request made to %s to client", request.URL.Path)`.

2023-04-18 00:00 UTC, lthibault approved these changes
LGTM 👍

2023-04-18 00:01 UTC, merged